/*
An array is an
object. Special type
-Data is stred in 
  key and value
-In an object
 you choose or create the 
 keys.
->The keys are created
 automatically
->You can only use
 bracket notation
->The keys
are sequential 
and are only numbers
->for the key autogenerated
->for the value
it can be anyother datatype
including ->
object,arrays,function
*/

/*
To create an array
let <variableName>=[]
*/

/*
We are going to create
an array to store 
datatypes we have learned
->number:favNumber
->string:favMovie or song
->are you male:boolean
->null: empty value
->object:favCar 
->fav 3 numbers: as an array
->function: aleter for goodmorning

->console.log ->
->console.table ->
*/

let learnStuff = [
  4,
  "Kids Next Door",
  true,
  null,
  {
    manufacture: "Toyota",
    model: "Hilux",
  },
  [2, 3, 7],
  function goodMorning() {
    alert("Good morning");
  },
];

console.table(learnStuff);

/*
 Access or read items from an
 array-> Bracket Notation
 Just like objects
 you need the key
 to read or access->
*/

/*
 For your array learnStuff
 go through everything
 -> using keys:numbers
 ->console.log each item
 ->for the function 
    -console.log
    ->calll the function
 -> for the array inside the
    also navigate through
    each item.
*/
//--> updating existing items
//---> array.length
/*
  Update existing item->
  -> update atleast 3 things in
  your array
*/

// learnStuff[0] = 44;

/*
 Add an item
 ->manual:know next position
  add an item using
  .length property
  and using  a new postion
 -> using the push method
    recormended
*/

// learnStuff[learnStuff.length] = "New thing";
// //

// learnStuff[56] = "new thing";

learnStuff.push("Add something", 45, 445);
